package com.lue.jeptags.entity;

import java.util.HashMap;

/**
 *
 * @author lue
 */
public class CountryList {

    public static HashMap getCountryList() {
        HashMap<String, String> country = new HashMap<>();
        country.put("AF", "Afghanistan");
        country.put("AX", "Åland Islands");
        country.put("AL", "Albania");
        country.put("DZ", "Algeria");
        country.put("AD", "Andorra");
        country.put("AO", "Angola");
        country.put("AI", "Anguilla");
        country.put("AQ", "Antarctica");
        country.put("AG", "Antigua and Barbuda");
        country.put("AR", "Argentina");
        country.put("AM", "Armenia");
        country.put("AW", "Aruba");
        country.put("AU", "Australia");
        country.put("AT", "Austria");
        country.put("AZ", "Azerbaijan");
        country.put("BS", "Bahamas");
        country.put("BH", "Bahrain");
        country.put("BD", "Bangladesh");
        country.put("BB", "Barbados");
        country.put("BY", "Belarus");
        country.put("BE", "Belgium");
        country.put("PW", "Belau");
        country.put("BZ", "Belize");
        country.put("BJ", "Benin");
        country.put("BM", "Bermuda");
        country.put("BT", "Bhutan");
        country.put("BO", "Bolivia");
        country.put("BQ", "Bonaire");
        country.put("BA", "Bosnia and Herzegovina");
        country.put("BW", "Botswana");
        country.put("BV", "Bouvet Island");
        country.put("BR", "Brazil");
        country.put("IO", "British Indian Ocean Territory");
        country.put("VG", "British Virgin Islands");
        country.put("BN", "Brunei");
        country.put("BG", "Bulgaria");
        country.put("BF", "Burkina Faso");
        country.put("BI", "Burundi");
        country.put("KH", "Cambodia");
        country.put("CM", "Cameroon");
        country.put("CA", "Canada");
        country.put("CV", "Cape Verde");
        country.put("KY", "Cayman Islands");
        country.put("CF", "Central African Republic");
        country.put("TD", "Chad");
        country.put("CL", "Chile");
        country.put("CN", "China");
        country.put("CX", "Christmas Island");
        country.put("CC", "Cocos (Keeling) Islands");
        country.put("CO", "Colombia");
        country.put("KM", "Comoros");
        country.put("CG", "Congo (Brazzaville)");
        country.put("CD", "Congo (Kinshasa)");
        country.put("CK", "Cook Islands");
        country.put("CR", "Costa Rica");
        country.put("HR", "Croatia");
        country.put("CU", "Cuba");
        country.put("CW", "CuraÇao");
        country.put("CY", "Cyprus");
        country.put("CZ", "Czech Republic");
        country.put("DK", "Denmark");
        country.put("DJ", "Djibouti");
        country.put("DM", "Dominica");
        country.put("DO", "Dominican Republic");
        country.put("EC", "Ecuador");
        country.put("EG", "Egypt");
        country.put("SV", "El Salvador");
        country.put("GQ", "Equatorial Guinea");
        country.put("ER", "Eritrea");
        country.put("EE", "Estonia");
        country.put("ET", "Ethiopia");
        country.put("FK", "Falkland Islands");
        country.put("FO", "Faroe Islands");
        country.put("FJ", "Fiji");
        country.put("FI", "Finland");
        country.put("FR", "France");
        country.put("GF", "French Guiana");
        country.put("PF", "French Polynesia");
        country.put("TF", "French Southern Territories");
        country.put("GA", "Gabon");
        country.put("GM", "Gambia");
        country.put("GE", "Georgia");
        country.put("DE", "Germany");
        country.put("GH", "Ghana");
        country.put("GI", "Gibraltar");
        country.put("GR", "Greece");
        country.put("GL", "Greenland");
        country.put("GD", "Grenada");
        country.put("GP", "Guadeloupe");
        country.put("GT", "Guatemala");
        country.put("GG", "Guernsey");
        country.put("GN", "Guinea");
        country.put("GW", "Guinea-Bissau");
        country.put("GY", "Guyana");
        country.put("HT", "Haiti");
        country.put("HM", "Heard Island and McDonald Islands");
        country.put("HN", "Honduras");
        country.put("HK", "Hong Kong");
        country.put("HU", "Hungary");
        country.put("IS", "Iceland");
        country.put("IN", "India");
        country.put("ID", "Indonesia");
        country.put("IR", "Iran");
        country.put("IQ", "Iraq");
        country.put("IE", "Republic of Ireland");
        country.put("IM", "Isle of Man");
        country.put("IL", "Israel");
        country.put("IT", "Italy");
        country.put("CI", "Ivory Coast");
        country.put("JM", "Jamaica");
        country.put("JP", "Japan");
        country.put("JE", "Jersey");
        country.put("JO", "Jordan");
        country.put("KZ", "Kazakhstan");
        country.put("KE", "Kenya");
        country.put("KI", "Kiribati");
        country.put("KW", "Kuwait");
        country.put("KG", "Kyrgyzstan");
        country.put("LA", "Laos");
        country.put("LV", "Latvia");
        country.put("LB", "Lebanon");
        country.put("LS", "Lesotho");
        country.put("LR", "Liberia");
        country.put("LY", "Libya");
        country.put("LI", "Liechtenstein");
        country.put("LT", "Lithuania");
        country.put("LU", "Luxembourg");
        country.put("MO", "Macao S.A.R.");
        country.put("MK", "Macedonia");
        country.put("MG", "Madagascar");
        country.put("MW", "Malawi");
        country.put("MY", "Malaysia");
        country.put("MV", "Maldives");
        country.put("ML", "Mali");
        country.put("MT", "Malta");
        country.put("MH", "Marshall Islands");
        country.put("MQ", "Martinique");
        country.put("MR", "Mauritania");
        country.put("MU", "Mauritius");
        country.put("YT", "Mayotte");
        country.put("MX", "Mexico");
        country.put("FM", "Micronesia");
        country.put("MD", "Moldova");
        country.put("MC", "Monaco");
        country.put("MN", "Mongolia");
        country.put("ME", "Montenegro");
        country.put("MS", "Montserrat");
        country.put("MA", "Morocco");
        country.put("MZ", "Mozambique");
        country.put("MM", "Myanmar");
        country.put("NA", "Namibia");
        country.put("NR", "Nauru");
        country.put("NP", "Nepal");
        country.put("NL", "Netherlands");
        country.put("AN", "Netherlands Antilles");
        country.put("NC", "New Caledonia");
        country.put("NZ", "New Zealand");
        country.put("NI", "Nicaragua");
        country.put("NE", "Niger");
        country.put("NG", "Nigeria");
        country.put("NU", "Niue");
        country.put("NF", "Norfolk Island");
        country.put("KP", "North Korea");
        country.put("NO", "Norway");
        country.put("OM", "Oman");
        country.put("PK", "Pakistan");
        country.put("PS", "Palestinian Territory");
        country.put("PA", "Panama");
        country.put("PG", "Papua New Guinea");
        country.put("PY", "Paraguay");
        country.put("PE", "Peru");
        country.put("PH", "Philippines");
        country.put("PN", "Pitcairn");
        country.put("PL", "Poland");
        country.put("PT", "Portugal");
        country.put("QA", "Qatar");
        country.put("RE", "Reunion");
        country.put("RO", "Romania");
        country.put("RU", "Russia");
        country.put("RW", "Rwanda");
        country.put("BL", "Saint Barthélemy");
        country.put("SH", "Saint Helena");
        country.put("KN", "Saint Kitts and Nevis");
        country.put("LC", "Saint Lucia");
        country.put("MF", "Saint Martin (French part)");
        country.put("SX", "Saint Martin (Dutch part)");
        country.put("PM", "Saint Pierre and Miquelon");
        country.put("VC", "Saint Vincent and the Grenadines");
        country.put("SM", "San Marino");
        country.put("ST", "São Tomé and Príncipe");
        country.put("SA", "Saudi Arabia");
        country.put("SN", "Senegal");
        country.put("RS", "Serbia");
        country.put("SC", "Seychelles");
        country.put("SL", "Sierra Leone");
        country.put("SG", "Singapore");
        country.put("SK", "Slovakia");
        country.put("SI", "Slovenia");
        country.put("SB", "Solomon Islands");
        country.put("SO", "Somalia");
        country.put("ZA", "South Africa");
        country.put("GS", "South Georgia/Sandwich Islands");
        country.put("KR", "South Korea");
        country.put("SS", "South Sudan");
        country.put("ES", "Spain");
        country.put("LK", "Sri Lanka");
        country.put("SD", "Sudan");
        country.put("SR", "Suriname");
        country.put("SJ", "Svalbard and Jan Mayen");
        country.put("SZ", "Swaziland");
        country.put("SE", "Sweden");
        country.put("CH", "Switzerland");
        country.put("SY", "Syria");
        country.put("TW", "Taiwan");
        country.put("TJ", "Tajikistan");
        country.put("TZ", "Tanzania");
        country.put("TH", "Thailand");
        country.put("TL", "Timor-Leste");
        country.put("TG", "Togo");
        country.put("TK", "Tokelau");
        country.put("TO", "Tonga");
        country.put("TT", "Trinidad and Tobago");
        country.put("TN", "Tunisia");
        country.put("TR", "Turkey");
        country.put("TM", "Turkmenistan");
        country.put("TC", "Turks and Caicos Islands");
        country.put("TV", "Tuvalu");
        country.put("UG", "Uganda");
        country.put("UA", "Ukraine");
        country.put("AE", "United Arab Emirates");
        country.put("GB", "United Kingdom (UK)");
        country.put("US", "United States (US)");
        country.put("UY", "Uruguay");
        country.put("UZ", "Uzbekistan");
        country.put("VU", "Vanuatu");
        country.put("VA", "Vatican");
        country.put("VE", "Venezuela");
        country.put("VN", "Vietnam");
        country.put("WF", "Wallis and Futuna");
        country.put("EH", "Western Sahara");
        country.put("WS", "Western Samoa");
        country.put("YE", "Yemen");
        country.put("ZM", "Zambia");
        country.put("ZW", "Zimbabwe");
        return country;

    }
}
